name: wike
base: core22
adopt-info: wike
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64

slots:
  wike:
    interface: dbus
    bus: session
    name: com.github.hugolabe.Wike

apps:
  wike:
    command: usr/bin/wike
    extensions: [gnome]
    environement:
      PYTHONPATH: ${SNAP}/usr/lib/python3/dist-packages:$PYTHONPATH
    plugs:
      - home
      - audio-playback
      - network
      - network-status
      - network-bind
      - optical-drive
      - removable-media
    common-id: com.github.hugolabe.Wike
    desktop: usr/share/applications/com.github.hugolabe.Wike.desktop
        
parts:
  wike:
    source: https://github.com/hugolabe/Wike.git
    source-tag: 1.8.2
    plugin: meson
    parse-info: [usr/share/metainfo/com.github.hugolabe.Wike.metainfo.xml]
    meson-parameters:
      - --prefix=/snap/wike/current/usr
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
    override-build: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/wike/current/usr/bin/wike
    organize:
      snap/wike/current/usr: usr  
    
 
