name: wike
base: core22
adopt-info: wike
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
layout: 
  /usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.0
  /usr/bin/python3.10:
    bind-file: $SNAP/usr/bin/python3.10
  

slots:
  wike:
    interface: dbus
    bus: session
    name: com.github.hugolabe.Wike

apps:
  wike:
    command: usr/bin/wike
    extensions: [gnome]
    environment:
      PYTHONPATH: ${SNAP}/usr/lib/python3/dist-packages:$PYTHONPATH
    plugs:
      - home
      - audio-playback
      - raw-usb
      - network
      - network-status
      - network-bind
      - optical-drive
      - removable-media
    common-id: com.github.hugolabe.Wike
    desktop: usr/share/applications/com.github.hugolabe.Wike.desktop
    
    
parts:
  wike:
    source: https://github.com/hugolabe/Wike.git
    after: [webkit]
    plugin: meson
    parse-info: [usr/share/metainfo/com.github.hugolabe.Wike.metainfo.xml]
    meson-parameters:
      - --prefix=/snap/wike/current/usr
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/wike/current/usr/bin/wike
    organize:
      snap/wike/current/usr: usr
  
  gnu-which:
    source: https://ftp.gnu.org/gnu/which/which-2.21.tar.gz
    plugin: make
    make-parameters:
      - -prefix=/usr
    build-packages:
      - build-essential
    
  webkit:
    source: https://webkitgtk.org/releases/webkitgtk-2.38.6.tar.xz
    after: [gnu-which]
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_SKIP_RPATH=ON
      - -DPORT=GTK    
      - -DLIB_INSTALL_DIR=/usr/lib  
      - -DUSE_LIBHYPHEN=OFF         
      - -DENABLE_GAMEPAD=OFF        
      - -DENABLE_MINIBROWSER=ON     
      - -DENABLE_DOCUMENTATION=OFF  
      - -DUSE_WOFF2=OFF             
      - -DUSE_GTK4=ON               
      - -DUSE_WPE_RENDERER=ON       
      - -DENABLE_JOURNALD_LOG=OFF   
      - -DENABLE_BUBBLEWRAP_SANDBOX=OFF 
      - -Wno-dev -G Ninja  
    build-snaps:
      - cmake
      - ruby
    build-packages:
      - build-essential
      - libsecret-1-dev
      - libcairo2-dev
      - libopenjp2-7-dev
      - libgudev-1.0-dev
      - sqlite3
      - libenchant-2-voikko
      - libwebp-dev
      - libsoup-3.0-dev
      - libtasn1-6-dev
      - libwpebackend-fdo-1.0-dev
      - libgeoclue-2-dev
      - hicolor-icon-theme
      - libavif-dev
      - libegl1-mesa-dev
      - libglu1-mesa-dev
      - unifdef
      
   
      
      
      
      
