name: wike
base: core22
adopt-info: wike
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
      bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: $PYTHONPATH:${SNAP}/usr/lib/python3/dist-packages

slots:
  wike:
    interface: dbus
    bus: session
    name: com.github.hugolabe.Wike

apps:
  wike:
    command: usr/bin/wike
    extensions: [gnome]
    plugs:
      - audio-playback
      - network
      - network-status
      - unity7
    common-id: com.github.hugolabe.Wike
    desktop: usr/share/applications/com.github.hugolabe.Wike.desktop
        
parts:
  wike:
    source: https://github.com/hugolabe/Wike.git
    source-tag: 1.8.3
    plugin: meson
    parse-info: [usr/share/metainfo/com.github.hugolabe.Wike.metainfo.xml]
    meson-parameters:
      - --prefix=/snap/wike/current/usr
    stage-packages:
      - python3-dbus
      - python3-requests
    override-build: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/wike/current/usr/bin/wike
      rm -rf usr/share/man
      rm -rf usr/share/doc
    organize:
      snap/wike/current/usr: usr  
    
 
