name: wike
base: core22
adopt-info: wike
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
    build-for: amd64
layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET-linux-gnu/webkit2gtk-4.1:
     bind: $SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/webkit2gtk-4.1
  /usr/lib/$CRAFT_ARCH_TRIPLET-linux-gnu/libwebkit2gtk-4.1.so:
     symlink: $SNAP/gnome-platform/usr/lib/x86_64-linux-gnu/libwebkit2gtk-4.1.so

environment:
  # WORKAROUND: Add python modules in Snap to search path
  PYTHONPATH: ${SNAP}/usr/lib/python3/dist-packages:$PYTHONPATH

slots:
  wike:
    interface: dbus
    bus: session
    name: com.github.hugolabe.Wike

apps:
  wike:
    command: usr/bin/wike
    extensions: [gnome]
    plugs:
      - home
      - audio-playback
      - raw-usb
      - network
      - network-status
      - network-bind
      - optical-drive
      - removable-media
    common-id: com.github.hugolabe.Wike
    desktop: usr/share/applications/com.github.hugolabe.Wike.desktop
        
parts:
  wike:
    source: https://github.com/hugolabe/Wike.git
    after: [webkit]
    plugin: meson
    parse-info: [usr/share/metainfo/com.github.hugolabe.Wike.metainfo.xml]
    meson-parameters:
      - --prefix=/snap/wike/current/usr
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
    override-build: |
      craftctl default
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/wike/current/usr/bin/wike
    organize:
      snap/wike/current/usr: usr  
    
  webkit:
    source: https://webkitgtk.org/releases/webkitgtk-2.40.1.tar.xz
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_SKIP_RPATH=ON
      - -DPORT=GTK    
      - -DLIB_INSTALL_DIR=/usr/lib  
      - -DUSE_LIBHYPHEN=OFF         
      - -DENABLE_GAMEPAD=OFF        
      - -DENABLE_MINIBROWSER=ON     
      - -DENABLE_DOCUMENTATION=OFF  
      - -DUSE_WOFF2=OFF             
      - -DUSE_GTK4=ON               
      - -DUSE_WPE_RENDERER=ON       
      - -DENABLE_JOURNALD_LOG=OFF
      - -Wno-dev -G Ninja  
    build-snaps:
      - cmake
      - ruby
      - ubuntu-make
    build-packages:
      - ccache
      - bubblewrap
      - xdg-dbus-proxy
      - libseccomp-dev
      - jdupes
      - libglib2.0-dev
      - libharfbuzz-dev
      - libcairo2-dev
      - libfontconfig-dev
      - libfreetype-dev
      - libicu-dev
      - libgcrypt20-dev
      - libhyphen-dev
      - liblcms2-dev
      - libmanette-0.2-dev
      - libxslt1-dev
      - libxml2-dev
      - libsoup2.4-dev
      - libsoup-3.0-dev
      - libgtk-3-dev
      - libgtk-4-dev
      - libsqlite3-dev
      - libsystemd-dev
      - libgudev-1.0-dev
      - libwoff-dev
      - libwpebackend-fdo-1.0-dev
      - gperf
      - bison
      - flex
      - unifdef
      - libavif-dev
      - libjpeg-dev
      - libopenjp2-7-dev
      - libpng-dev
      - libtasn1-6-dev
      - libwebp-dev
      - libxt-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libenchant-2-dev
      - libsecret-1-dev
      - gobject-introspection
      - libgirepository1.0-dev
      - libegl-dev
      - libgl-dev
      - libgles-dev
    override-build: |
      craftctl default
      rm -rf * .[^.]*
      sed '/m_brush =/s/{/Brush {/' \
          -i Source/WebCore/platform/graphics/SourceBrush.cpp
