name: wike
base: core22
adopt-info: wike
grade: stable
confinement: strict
compression: lzo
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
layout: 
  /usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.0:
    bind: $SNAP/gnome-platform/usr/lib/$CRAFT_ARCH_TRIPLET/webkit2gtk-4.0
  
slots:
  wike:
    interface: dbus
    bus: session
    name: com.github.hugolabe.Wike

apps:
  wike:
    command: usr/bin/wike
    extensions: [gnome]
    environment:
      PYTHONPATH: ${SNAP}/usr/lib/python3/dist-packages:$PYTHONPATH
    plugs:
      - home
      - audio-playback
      - raw-usb
      - network
      - network-status
      - network-bind
      - optical-drive
      - removable-media
    common-id: com.github.hugolabe.Wike
    desktop: usr/share/applications/com.github.hugolabe.Wike.desktop
    
    
parts:
  wike:
    source: https://github.com/hugolabe/Wike.git
    plugin: meson
    parse-info: [usr/share/metainfo/com.github.hugolabe.Wike.metainfo.xml]
    meson-parameters:
      - --prefix=/snap/wike/current/usr
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=0)
    override-build: |
      craftctl default
      sed -e '1c#!/usr/bin/env python3' -i ${CRAFT_PART_INSTALL}/snap/wike/current/usr/bin/wike
    organize:
      snap/wike/current/usr: usr
    stage-packages:
      - gir1.2-webkit2-4.1
      
      
